# Generated by Django 5.2.1 on 2025-05-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='person_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.person'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.payment'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.plan'),
        ),
    ]
