# Generated by Django 5.2.1 on 2025-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_payment_expense_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='person_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
