# Generated by Django 5.2.1 on 2025-06-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_expense_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expense',
        ),
    ]
